### ISSUE TITLE
Some issues with the Mod Menu

### ISSUE THREAD

**Issue by TubBuddy** [TheUnknownCod3r/BO4-Lucy-Menu#4]
Great menu! But as i was testing stuff in the menu i found out that the wunderwaffle does not work along with "Tele zombies infront of you" which just crashes the game. As a bonus it would also be great if you could add homonculus, samantha box, matryoshka Dolls and monkeys to every map along with the Winters Howl 👍

**Comment by TheUnknownCod3r** [comment]
Thank you for the feedback!

Its very possible I have the wrong stringname for the Wunderwaffle, I shall look into it when I get a chance, iirc it should be something to do with tesla, so I'll check my notes. 

I can definitely see about adding the others, the Homonculus should be easy enough for Chaos, I planned to get it added anyway, however certain weapons only work on some maps due to storyline restrictions, so it won't be for every map. Monkeys are Aether only, Homonculus are Chaos only iirc. Not sure about Dolls or the Samantha Box, i'd have to check that but id assume its the same position.

Tele Zombies shouldn't crash you, I'll look into that asap, and get a fix out for it. Thanks for letting me know.

**Comment by TheUnknownCod3r** [comment]
Fixed as of the latest Push, please download the update, and try the options again! :D

**Comment by TubBuddy** [comment]
Thanks for the fast response! But sorry Nothing changed, Wunderwaffle still doesnt work and it still crashes when using zombies tele in front of you 🤔 i also sure wish there would be a no clip feature! Thanks!

**Comment by TubBuddy** [comment]
self addOpt("Zeus", &BO4NewOrigin, (1993.89, -479.343, 212.125), "Zeus");
                    self addOpt("Odin", &BO4NewOrigin, (2020.7, 341.974, 215.125), "Odin");
                    self addOpt("Ra", &BO4NewOrigin, (-1809.33, 423.894, 212.125), "Ra");
                    self addOpt("Danu", &BO4NewOrigin, (-1922.34, -443, 216.313), "Danu");
                    self addOpt("Challenge Podium", &BO4NewOrigin, (58.3157, -24.4512, 80.125), "Challenge Podium");
                    self addOpt("The Pit", &BO4NewOrigin, (151.776, 1802.6, -365.875), "The Pit");
                    
                    This is for IX^
                    
                    self addOpt("Poop Deck", &BO4NewOrigin, (6.67061, 4843.74, 1216.12), "Poop Deck");
                    self addOpt("Boiler Room", &BO4NewOrigin, (8.88611, 622.069, 320.125), "Boiler Room");  
                    self addOpt("Dining Hall", &BO4NewOrigin, (-457.054, -775.388, 1056.13), "Dining Hall");
                    self addOpt("1st Class Lounge", &BO4NewOrigin, (-160.682, -612.253, 1216.13), "1st Class Lounge");
                    self addOpt("Forecastle", &BO4NewOrigin, (118.374, -4506.12, 928.125), "Forecastle");
                    
                    This is for Voyage
                    
                    👍 😄

**Comment by TheUnknownCod3r** [comment]
Sounds like a local issue then, as works for me. In fact, teleport zombies was changed cause I did something and don’t remember, so I reset it to the original method. I’d delete your copy and try again.

**Comment by TheUnknownCod3r** [comment]
tested to confirm, Teleport Zombies works fine, Ive used it on Blood and Tag in testing this morning. You are correct however, I assume both myself and SirCryptic have the wrong stringname for the Wunderwaffle, so Ill look into it again. It worked in testing, so not sure what happened.

**Comment by TubBuddy** [comment]
ok good news the tele in front works! 
The Wunderwaffle gun is actually wrong its "ww_tesla_sniper_t8" 
Also it would b cool if u added "_upgraded" at the ends of all the kraken variants and MK2 variants on AO!
ill probs do more tele for other maps if u want that? I did Voyages too but i believe u didn't add that.  
quick question also: Is it possible to spawn catalysts with the mod menu?

**Comment by TheUnknownCod3r** [comment]
I plan to add them all into a separate menu inside upgraded weapons, I just never got around to it yet, so I'll get there eventually.

The Wonderwaffe is correct, it was originally ww_tesla_sniper_t8, when you opened the issue. I went into a game, and manually grabbed the correct name for it. 

If you'd like to, you're more than welcome to supply features, I kept it open source for that reason! Just make a fork, add and test them, then submit a pull request! :D

I haven't looked into it, im assuming there's a function for it, but it'll be in the hashed scripts if anywhere. If you can find it, you could definitely do it, its just trial and error on how to actually call it correctly. Im still looking into spawning Blightfathers with Correct AI, etc.

**Comment by TubBuddy** [comment]
Thats weird cuz when i used it its not the sniper ww and there is no sound on it.

![ww](https://user-images.githubusercontent.com/127999838/226753525-c6e0d719-4e52-49ce-a0fe-bda331866696.PNG)

Thanks! ill make a fork when teles are done and its a bit more updated!

heres a few more teles!!! :D

DOTN

self addOpt("Sentinal Artifact", &BO4newOrigin, (-2.56008, -928.784, -7.875), "Sentinal Artifact");
                    self addOpt("North Atrium Bridge", &BO4newOrigin, (11.2006, 956.359, 25.7624), "North Atrium Bridge");
                    self addOpt("Bedroom", &BO4newOrigin, (1727.24, 1165.29, -7.875), "Bedroom");
                    self addOpt("Wine Cellar", &BO4newOrigin, (-249.745, -1334.12, -415.875), "Wine Cellar");
                    self addOpt("Mausoleum", &BO4newOrigin, (-4474.56, 524.39, 272.125), "Mausoleum");
                    self addOpt("Library", &BO4newOrigin, (-1512.27, 485.992, -209.684), "Library");
                    self addOpt("Greenhouse Laboratories", &BO4newOrigin, (4356.48, -73.3307, -439.875), "Greenhouse Laboratories");
                    self addOpt("Forest", &BO4newOrigin, (-13.9522, 5562.84, -783.936), "Forest");
                    
AE

self addOpt("Temple of Apollo", &BO4newOrigin, (-786.167, -867.222, 64.125), "Temple of Apollo");
                    self addOpt("Amphitheater", &BO4newOrigin, (-1990.29, 1212.24, 252.125), "Amphitheater");
                    self addOpt("Spartan Monument", &BO4newOrigin, (803.154, -4110.64, -815.908), "Spartan Monument");
                    self addOpt("River of Sorrow", &BO4newOrigin, (-1220.23, 6305.58, 946.825), "River of Sorrow");
                    self addOpt("Cliff Ruins", &BO4newOrigin, (-2715.52, 7363.74, 527.862), "Cliff Ruins");
                    self addOpt("Python Pass", &BO4newOrigin, (202.279, 8547.08, 434.117), "Python Pass");

**Comment by TheUnknownCod3r** [comment]
Not sure, as I say it was initially the tesla_sniper stringname, so maybe it did work. I guess ill check it. as for the teleports, just fork, add them, then PR. Its cleaner, and adds you to Credit correctly since you're doing stuff too. :)

**Comment by TubBuddy** [comment]
Ahhhh ok i was confused lol. I was also wondering if there is gonna be a noclip feature in the near future?

**Comment by TheUnknownCod3r** [comment]
Yeah Ill get to it, I never added it cause I dont really have a need for it, but a few people mentioned it now so Ill do it tomorrow.
